
# Build site settings
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
title: Machine Learning
description: This is a github to store my Introduction to Machine Learning projects from my CS 4375.003 class. 
show_downloads: true
