---
title: "Classification"
student: "Isabelle Kirby", "Bridgette Bryant" 
NetID: "IRK180000", "BMB180001"
Assignment: "Linear Models"
Date: "09/16/2021"
---
Loading in file
```{r}
df <- read.csv("covtype.csv")
```

Now we are creating the training and testing sets (80% train, 20% test).
```{r}
i <- sample(1:nrow(df), nrow(df)*.80, replace=FALSE)
train <- df[i,]
test <- df[-i,]

```
Data Exploration
```{r}
head(train)
tail(train)

median(train$class)

mode(train$cap.color)

str(train)
```
Plots
```{r}
hist(train$Elevation)
hist(train$Soil_Type)
slices <- c(sum(train$Wilderness_Area1==1, na.rm=TRUE), sum(train$Wilderness_Area2==1, na.rm=TRUE), sum(train$Wilderness_Area3==1, na.rm=TRUE), sum(train$Wilderness_Area4==1, na.rm=TRUE))

labls <- c("Wilds 1","Wilds 2","Wilds 3","Wilds 4")
pie(slices,labels = labls, main="Types of Wild Area", col=c("green", "blue", "yellow", "red"))

```
Logistic Regression
```{r}
tree_type1 <- df
tree_type1$Cover_Type <- as.factor(ifelse (tree_type1$Cover_Type=="1",1,0))

fun <- function(dataf){
  glm1 <- glm(Cover_Type~., data=train, family=poisson())
  probs <- predict(glm1, newdata=test)
  pred <- ifelse(probs>0.5, 1, 0)
  acc <- mean(pred==test$Cover_Type)
  print(paste("accuracy = ", acc))
  table(pred, test$Cover_Type)
}

fun(tree_type1)


#glm1 <- glm(Slope~Elevation, data=train, family=poisson())
#summary(glm1)
```


Naive Bayes
```{r}
library(e1071)
nb1 <- naiveBayes(Slope~., data=train)
nb1
```

